name: mac_dt
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  provider: ^6.0.4
  http: ^0.13.5
  table_calendar: ^3.0.8
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_analytics: ^10.0.6


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/wallpapers/
    - assets/icons/
    - assets/appsMac/
    - assets/appsiOS/
    - assets/caches/
    - assets/messages/
    - assets/apps/
    - assets/sysPref/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SF
      fonts:
      - asset: assets/fonts/SF/SFUltralight.otf
        weight: 100
      - asset: assets/fonts/SF/SFLight.otf
        weight: 300
      - asset: assets/fonts/SF/SFThin.otf
        weight: 200
      - asset: assets/fonts/SF/SFRegular.otf
        weight: 400
      - asset: assets/fonts/SF/SFMedium.otf
        weight: 500
      - asset: assets/fonts/SF/SFSemibold.otf
        weight: 600
      - asset: assets/fonts/SF/SFBold.otf
        weight: 700
      - asset: assets/fonts/SF/SFHeavy.otf
        weight: 800
      - asset: assets/fonts/SF/SFBlack.otf
        weight: 900

    - family: SFR
      fonts:
      - asset: assets/fonts/SFRounded.ttf
        weight: 500
    - family: Helvetica
      fonts:
      - asset: assets/fonts/Helvetica.ttf
        weight: 100
      - asset: assets/fonts/Helvetica-Bold.ttf
        weight: 500
    - family: HN
      fonts:
        - asset: assets/fonts/HN/HNUltraLight.ttf
          weight: 100
        - asset: assets/fonts/HN/HNThin.ttf
          weight: 200
        - asset: assets/fonts/HN/HNLight.ttf
          weight: 300
        - asset: assets/fonts/HN/HNRegular.ttf
          weight: 400
        - asset: assets/fonts/HN/HNMedium.ttf
          weight: 500
        - asset: assets/fonts/HN/HNBold.ttf
          weight: 600
        - asset: assets/fonts/HN/HNHeavy.ttf
          weight: 700
        - asset: assets/fonts/HN/HNBlack.ttf
          weight: 800
        - asset: assets/fonts/HN/HNExtraBlack.ttf
          weight: 900
    - family: Menlo
      fonts:
        - asset: assets/fonts/Menlo-Regular.ttf
          weight: 500



  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
